### ISSUE TITLE
Setup Travis CI job to test PRs

### ISSUE THREAD

**Issue by vlsi** [jvm-profiling-tools/honest-profiler#144]
Travis might be a good approach to cope with regression testing, publishing build results, etc

**Comment by RichardWarburton** [comment]
I like - I've not tried building native code with travis though.

**Comment by nitsanw** [comment]
We could take note from async-profiler which has this setup. Would also be good to run a MacOS build.

**Comment by RichardWarburton** [comment]
Yeah, that's a pretty good idea. Especially since my trust for people not breaking the build is too high.

**Comment by nitsanw** [comment]
slightly stupid here, looks like the config file is here and all, just need to update Travis

**Comment by nitsanw** [comment]
Enabled now:
https://travis-ci.org/jvm-profiling-tools/honest-profiler

**Comment by ikavalio** [comment]
Hey guys, I committed travis config a some time ago to test agent on oldest gcc/clang versions available at that time. I believe OS X specific settings might need some refactoring.
