### ISSUE TITLE
cmake build still failed on OSX

### ISSUE THREAD

**Issue by chhsiao90** [jvm-profiling-tools/honest-profiler#174]
I uninstall unittest-cpp installed from homebrew and re-installed it from source code at latest commit of the master branch.

But it's still failed.

It seems that ```UnitTest++Config.cmake``` will set UTPP_INCLUDE_DIRS to the correct path.
But our cmake script will still take ```unittest++_INCLUDE_DIRS``` to find the header files.
ref: [CMakeLists.txt#L44](https://github.com/RichardWarburton/honest-profiler/blob/master/CMakeLists.txt#L44)

Please correct me if I'm doing wrong somewhere.
Or if the script's problem, I would like to create PR for this, thanks!

**Comment by chhsiao90** [comment]
FYI
I build unittest++ follow the steps [unittest-cpp/wiki/Building-Using-CMake](https://github.com/unittest-cpp/unittest-cpp/wiki/Building-Using-CMake)
After that, I could not build with current CMakeLists.txt settings,
but success after the modification of https://github.com/chhsiao90/honest-profiler/commit/83592625ddcbbef6cb7d8eb9c77b13984bba4237 on my OSX.

**Comment by nitsanw** [comment]
Travis shows this as passing
E.g: https://travis-ci.org/jvm-profiling-tools/honest-profiler/builds/336200155
