### ISSUE TITLE
Can't open Log Files > 2GB

### ISSUE THREAD

**Issue by PhRX** [jvm-profiling-tools/honest-profiler#175]
Apparently log files when opened are mapped to memory in their entirety using a single MappedByteBuffer, which clearly limits the allowed size of the file.

Instead, the FileLogSource should, in its read() method, return a buffer which acts as a moving window over the file. Large enough to never produce "Partial Records" in the LogParser, but not the entire file in one go.

**Comment by PhRX** [comment]
Fixed in branch "Fix_175" on fork https://github.com/PhRX/honest-profiler-fx-ui.

**Comment by PhRX** [comment]
Fixed by #208 acceptance.

**Comment by mattibickel** [comment]
Just let me say that's the second issue that gets closed while I'm looking at it. Keep up the pace folks, really appreciate it.
