### ISSUE TITLE
Sampling rate doesn't respect agent "interval=" configuration ?

### ISSUE THREAD

**Issue by PhRX** [jvm-profiling-tools/honest-profiler#177]
I just dumped the timeSec and timeNano values from the TraceStart events from 2 log files, one from a profile with "interval=7" and one with "interval=37" as parameters to the agent.

In both cases however, it seems that the TraceStart events are spaced exactly 4ms apart. A sample of the dump is included below.

You can see that within every second (the timeSec value), the difference in the ns part between consecutive samples is 4.000.000 ns (== 4 ms), give or take a few nanos.

Am I misinterpreting the interval parameter or is this an issue in the C++ code ?

[Start extract from log dumps]

with "interval=7" :
START -> s=1482937280 -- ns=795022230
START -> s=1482937280 -- ns=799022782
START -> s=1482937280 -- ns=803022228
START -> s=1482937280 -- ns=807022394
START -> s=1482937280 -- ns=811022981
START -> s=1482937280 -- ns=815022320

with "interval=37" :
START -> s=1484226307 -- ns=123449749
START -> s=1484226307 -- ns=123452869
START -> s=1484226307 -- ns=127450208
START -> s=1484226307 -- ns=131463782
START -> s=1484226307 -- ns=135468361
START -> s=1484226307 -- ns=139464120

**Comment by PhRX** [comment]
And I just checked to be sure : the number of traceStart events emitted from the log is equal to the number of samples, so no spurious traceStarts are emitted.

**Comment by ceeaspb** [comment]
@PhRX The sampling rate is implemented with setitimer:

https://github.com/RichardWarburton/honest-profiler/blob/3284cbe710f6d27d37033e1c74a3e9fd3e00d6d7/src/main/cpp/signal_handler.cpp#L36

The timer interval is dependent on the kernel.
Your minimum interval of 4ms sounds like a linux 2.6 kernel 250Hz tick rate.

see ```man setitimer``` etc

This might need documenting here
https://github.com/RichardWarburton/honest-profiler/wiki/How-to-Run

**Comment by nitsanw** [comment]
Should be fixed now, please retest.
