### ISSUE TITLE
Scheduling profiler interval failed with error 22

### ISSUE THREAD

**Issue by cless91** [jvm-profiling-tools/honest-profiler#258]
Hello,

>Starting sampling
>Scheduling profiler interval failed with error 22

I'm on the "embedded Ubuntu" on windows 10 and that error happens when i try to sample some springboot app.

the command i use is : java -agentpath:/home/{user}/honest-profiler/build/liblagent.so=interval=7,logPath={myModule_home}/log.hpl -jar target/{myModule}.jar

i did not encouter that problem on centOS. Any idea ?

**Comment by RichardWarburton** [comment]
I don't think you can use sigprof under WSL. I've tried before myself and it didn't work.
