### ISSUE TITLE
What are restrictions in async callback?

### ISSUE THREAD

**Issue by BigBabolBee** [jvm-profiling-tools/honest-profiler#277]
Hi,

As you mentioned in [_wiki - The Profiling Approach_](https://github.com/jvm-profiling-tools/honest-profiler/wiki/The-Profiling-Approach), there are restrictions in async callback. 

What are they exactly? 

Actually, I've met some trouble while implementing the signal handler with JVMTI which I think they come frome the restriction. Below is my code:

```
void signalHandler(...){
     ...
     vm->GetEnv(*jni, JNI_VERSION_1_6);
     
     pAGCT(&trace, MAXFRAMES, ucontext);      //invoke asyncGetCallTrace funciton
     if (trace.num_frames > ){
         jni->FindClass(...);
         jni->GetStaticMethodID(...);
         jni->CallStaticObjectMethod(...);
         ...
     }
}

void setSignalHandler(...){
    ...
    sa.sa_sigaction = &signalHandler;
    ...
}

JNIEXPORT jint JNICALL
Agent_OnAttach(...){
    ...
    enable_capabilities();
    set_callbacks();
    set_notif();
    setSignalHandler();
    setitimer(...);
}
```

The VM crashed when I was trying to attach this agent on a running program and I got SIGFPE or SIGSEGV signal in core dump. What i found in hs_err_pid.log is that the problematic frame is always in [libjvm.so]. This almost drives me mad.

Would you kindly explain why these crashes happened?

Thank you

**Comment by RichardWarburton** [comment]
This isn't an issue about Honest Profiler - it's a question about how to write your own profiler.
