### ISSUE TITLE
Compilation fails on Fedora

### ISSUE THREAD

**Issue by cykl** [jvm-profiling-tools/honest-profiler#64]
On Fedora unittest++'s headers are stored in `/usr/include/UnitTest++/` and not in `/usr/include/UnitTest++/`. It is easy to patch the Makefile but it would be nice to have it right from the beginning. Any idea about the best way to fix it ? (adding the two paths to TEST_INCLUDES, adding an ifeq...) 

```
diff --git a/Makefile b/Makefile
index ae7c048..a5a83b0 100644
--- a/Makefile
+++ b/Makefile
@@ -66,7 +66,7 @@ COPTS:=$(PLATFORM_COPTS) $(CXX_COPTS) $(GLOBAL_COPTS) $(PLATFORM_WARNINGS) \
 # TODO: consider re-adding in production -fno-exceptions

 INCLUDES+=-I /usr/include/i386-linux-gnu/c++/4.8/ -I$(JAVA_HOME)/$(HEADERS) -I$(JAVA_HOME)/$(HEADERS)/$(UNAME) 
-TEST_INCLUDES=$(INCLUDES) -I/usr/include/unittest++
+TEST_INCLUDES=$(INCLUDES) -I/usr/include/UnitTest++

 # LDFLAGS+=-Wl,--export-dynamic-symbol=Agent_OnLoad
```

**Comment by urisimchoni** [comment]
I believe this is fixed by PR 240

**Comment by RichardWarburton** [comment]
Thanks @urisimchoni. I'm closing the issue. If anyone spots this re-appearing then feel free to re-open.
